app/models.py
# Models are the Python classes that represent the db objects
from . import db

class Store(db.Model):
    id = db.Column(db.String(80), primary_key=True)
    name = db.Column(db.String(80), nullable=False, unique=True)

    def __repr__(self):
        return f'<Store {self.name}>'
    
    def to_dict(self):
        return {
            'id': self.id,
            'name': self.name,
        }

app/__init__.py
from config import Config
from flask import Flask
from flask_sqlalchemy import SQLAlchemy

# Create SQLAlchemy instance
db = SQLAlchemy()

def create_app():
    app = Flask(__name__)
    
    app.config.from_object(Config)
    app.secret_key = "356fP]}'I{oMOU[x5_X^-mD!V?~o.B"

    from .routes import main
    app.register_blueprint(main)    # Register the blueprint

    db.init_app(app)

    # Creates tables that do not exist in the db
    with app.app_context():
        db.create_all()

    return app

app/routes.py
from flask import Blueprint, current_app, jsonify, render_template, request, session

from app import db
from app.models import Store

from app.utils import google_places, overpass

main = Blueprint('main', __name__)

@main.route('/')
def home():
    return render_template('home.html')

@main.route('/search')
def search():
    return render_template('search.html')

@main.route('/save_location', methods=['POST'])
def set_location():
    data = request.get_json()
    session['location'] = {
        'latitude': data['latitude'],
        'longitude': data['longitude']
    }

    return jsonify({'status': 'success'})

@main.route('/get_location', methods=['GET'])
def get_location():
    location = session.get('location')
    lat = location['latitude']
    lon = location['longitude']

    if lat is not None and lon is not None:
        return jsonify({'latitude': lat, 'longitude': lon})
    else:
        return jsonify({'error': 'Location not set yet'}), 404
    
@main.route('/get_restaurants', methods=['GET'])
def get_restaurants():
    location = session.get('location')
    lat = location['latitude']
    lon = location['longitude']

    if not lat or not lon:
        return jsonify({'error': 'Missing coordinates'}), 400
    
    places = overpass.restaurants(lat, lon)
    return jsonify(places)

@main.route('/search_places', methods=['GET'])
def search_places():
    query = 'Ashfield restaurants'

    place_ids = google_places.find_place_ids(current_app.config['GOOGLE_PLACES_API_KEY'], query, 4.0)

    place_details = google_places.find_detailed_places(place_ids, current_app.config['GOOGLE_PLACES_API_KEY'])

    return jsonify(place_details)

@main.route('/find_filtered_places', methods=['POST'])
def find_filtered_places():
    data = request.get_json()
    query = data.get("query")
    rating = float(data.get("min_rating"))  # Optional if you want to use it
    open_time = data.get("open_time")  # Optional
    close_time = data.get("close_time")  # Optional

    # You can build a more specific query using rating/open_time/close_time if needed
    place_ids = google_places.find_place_ids(current_app.config['GOOGLE_PLACES_API_KEY'], query, rating)

    return jsonify({"place_ids": place_ids})

@main.route('/add')
def add():
    new_store = Store(id='abcdef', name='random store')
    db.session.add(new_store)
    db.session.commit()

    # For testing purposes, I want to print the table I just added to
    # Equivalent to SELECT * FROM user
    # stores = Store.query.all()
    # print(stores)

    return jsonify({'result': 'its okay!'})

@main.route('/find_stores')
def find_stores():
    # Equivalent to SELECT * FROM user
    stores = Store.query.all()

    json_data = [store.to_dict() for store in stores]
    return jsonify(json_data)

app/templates/home.html
<!DOCTYPE html>
<html>
    <head>
        <title>Home</title>
        <script src="/static/js/db.js"></script>
        <script src="/static/js/geolocate.js"></script>
        <script src="/static/js/restaurants.js"></script>
    </head>
    <body>
        <h1 style="text-align: center;">Welcome to the home!</h1>

        <p style="text-align: center;"> Click on the following button to go to search page.</p>
        <div style="text-align: center;">
            <a href="{{ url_for('main.search') }}">
                <button>Search Page</button>
            </a>
        </div>

        <p style="text-align: center;">Click on the following button to share your location.</p>
        <div style="text-align: center;">
            <button onclick="findGeolocation()">Share Location</button>
        </div>

        <p id="geolocation" style="text-align: center;">Geolocation</p>
        <div style="text-align: center;">
            <button onclick="getGeolocation()">Click to view lat and lon values</button>
        </div>

        <div style="text-align: center;">
            <button onclick="getRestaurants()">Find nearby restaurants</button>
        </div>

        <div style="text-align: center;">
            <button onclick="getGoogleRestaurants()">Find Google restaurants</button>
        </div>

        <div style="text-align: center;">
            <button onclick="addStore()">Add a store to our db - dummy for now</button>
        </div>

        <div style="text-align: center;">
            <button onclick="returnStores()">See what stores are stored inside db</button>
        </div>
    </body>
</html>

app/templates/search.html
<!DOCTYPE html>
<html>
    <head>
        <style>
            table {
                font-family: arial, sans-serif;
                border-collapse: collapse;
                width: 100%;
            }

            td, th {
                border: 1px solid #dddddd;
                text-align: left;
                padding: 8px;
            }

            tr:nth-child(even) {
                background-color: #dddddd;
            }
        </style>
        <title>Restaurant Search</title>
        <script src="/static/js/restaurants.js"></script>
    </head>
    <body>
        <h1 style="text-align: center;">Please enter the following stuff!</h1>

        <div style="text-align: center;">
            <label for="query">Query:</label>
            <input type="text" id="query" name="query">
            <br>
            
            <label for="min-rating">Minimum rating:</label>
            <select id="min-rating" name="rating">
                <option value="0">Any</option>
                <option value="4.5">4.5+</option>
                <option value="4.0">4.0+</option>
                <option value="3.5">3.5+</option>
                <option value="3.0">3.0+</option>
                <option value="2.5">2.5+</option>
                <option value="2.0">2.0+</option>
                <option value="1.5">1.5+</option>
                <option value="1.0">1.0+</option>
            </select>
            <br>

            <label for="open-time">Enter desired open time:</label>
            <input type="time" name="open-time" id="open-time" value="00:00">
            <br>

            <label for="close-time">Enter desired close time:</label>
            <input type="time" name="close-time" id="close-time" value="23:59">
            <br><br>

            <button onclick="findFilteredRestaurants()">Search Restaurants</button>
            <br><br>
        </div>

        <table id="resultsTable">
            <thead>
                <tr>
                    <th>ID</th>
                    <th>Name</th>
                    <th>Rating</th>
                </tr>
            </thead>
            <tbody>
                <!-- Dynamic rows will go here -->
            </tbody>
        </table>

        <br><br>

        <div style="text-align: center;">
            <a href="{{ url_for('main.home') }}">
                <button>Home</button>
            </a>
        </div>
    </body>
</html>